### ISSUE TITLE
Bound of confidence score for global correspondence of Gocor

### ISSUE THREAD

**Issue by ankitagr01** [PruneTruong/GOCor#3]
Hello, thank you for sharing the work, and congratulations. 
I wanted to understand the upper and lower bound of confidence score for Gocor global correspondence, I have implemented your method in my research and I get confidence range in [-2, +7] but sometimes only in the range of [-0.2, +0.3], so I wanted to understand when should I consider it to be a good match? or where should I put a bound to it? looking at the paper I understand that score <= 0 refers to non-match, but for positive confidence, there is no defined bound. 
Thank You

**Comment by PruneTruong** [comment]
Hi, in the paper, we never specifically threshold the confidence scores resulting from GOCor, since they are only used as a cue, inputted to the decoder to predict the flow. We therefore do not need to define any specific bound on what is considered a good or a bad match. Moreover, during training, all the labels (the y for the reference frame objective and the R for the query frame objective) are learned along with the other parameters of the network by the SGD-based minimization of the final network loss. Therefore, if you are training with different losses, or different datasets, the learnt y and R could be different, resulting in different ranges for the confidence scores which are optimized online, using y and R.   So basically, the confidence scores will take a range that best suits the network end task (and end loss used during training).
